parameters:
    xml_importer.class:    FeelUnique\Ordering\Importer\XmlImporter
    order_processor.class: FeelUnique\Ordering\OrderProcessor\OrderProcessor
    offer_processor.class: FeelUnique\Ordering\Offer\OfferProcessor
    offer_container.class: FeelUnique\Ordering\Offer\OfferContainer
    offer_checker.class:   FeelUnique\Ordering\Offer\OfferChecker

services:
    filesystem:
        class: Symfony\Component\Filesystem\Filesystem
    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
    xml_importer:
        class: "%xml_importer.class%"
    offer_container:
        class: "%offer_container.class%"
        arguments: [ "%offers%" ]
    offer_checker:
        class: "%offer_checker.class%"
        arguments: [ "@offer_container" ]
    offer_processor:
        class: "%offer_processor.class%"
        arguments: [ "@offer_container", "@offer_checker" ]
    order_processor:
        class: "%order_processor.class%"
        arguments: [ "@offer_processor" ]
